blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/whytcard-dev/Whytcard_discuss/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/whytcard-dev/Whytcard_discuss/tree/main/EN
    about: Check our documentation for more information. 